import mammoth from 'mammoth';

export interface DocxConversionResult {
  title: string;
  markdown: string;
}

/**
 * Convert any .docx (whether generated by this app or external) into
 * markdown suitable for revision-mode editing. Preserves heading levels,
 * paragraphs, basic emphasis, and lists.
 */
export async function docxToMarkdown(file: File): Promise<DocxConversionResult> {
  const arrayBuffer = await file.arrayBuffer();
  const { value: html } = await mammoth.convertToHtml({ arrayBuffer });
  const markdown = htmlToMarkdown(html);

  const title = extractTitle(markdown) || file.name.replace(/\.docx$/i, '');
  return { title, markdown };
}

function extractTitle(markdown: string): string {
  for (const line of markdown.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    const headingMatch = trimmed.match(/^#+\s+(.+)$/);
    if (headingMatch) return headingMatch[1].trim();
    return trimmed.slice(0, 120);
  }
  return '';
}

function htmlToMarkdown(html: string): string {
  const doc = new DOMParser().parseFromString(`<root>${html}</root>`, 'text/html');
  const root = doc.querySelector('root');
  if (!root) return '';
  return walk(root).trim().replace(/\n{3,}/g, '\n\n');
}

function walk(node: Node): string {
  if (node.nodeType === Node.TEXT_NODE) {
    return (node.textContent || '').replace(/\s+/g, ' ');
  }
  if (node.nodeType !== Node.ELEMENT_NODE) return '';

  const el = node as Element;
  const tag = el.tagName.toLowerCase();
  const inner = () => Array.from(el.childNodes).map(walk).join('');

  switch (tag) {
    case 'h1': return `\n\n# ${inner().trim()}\n\n`;
    case 'h2': return `\n\n## ${inner().trim()}\n\n`;
    case 'h3': return `\n\n### ${inner().trim()}\n\n`;
    case 'h4': return `\n\n#### ${inner().trim()}\n\n`;
    case 'h5': return `\n\n##### ${inner().trim()}\n\n`;
    case 'h6': return `\n\n###### ${inner().trim()}\n\n`;
    case 'p':  return `\n\n${inner().trim()}\n\n`;
    case 'br': return '\n';
    case 'strong':
    case 'b':  return `**${inner()}**`;
    case 'em':
    case 'i':  return `*${inner()}*`;
    case 'u':  return inner();
    case 'a': {
      const href = el.getAttribute('href') || '';
      const text = inner();
      return href ? `[${text}](${href})` : text;
    }
    case 'ul':
      return '\n' + Array.from(el.children)
        .filter((c) => c.tagName.toLowerCase() === 'li')
        .map((li) => `- ${walk(li).trim()}`)
        .join('\n') + '\n';
    case 'ol':
      return '\n' + Array.from(el.children)
        .filter((c) => c.tagName.toLowerCase() === 'li')
        .map((li, idx) => `${idx + 1}. ${walk(li).trim()}`)
        .join('\n') + '\n';
    case 'li':  return inner();
    case 'table':
    case 'thead':
    case 'tbody':
    case 'tr':
      return '\n' + inner() + '\n';
    case 'td':
    case 'th':
      return `${inner().trim()} | `;
    case 'root':
    case 'div':
    case 'span':
    case 'section':
    case 'article':
      return inner();
    default:
      return inner();
  }
}
